/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class CallSession extends SipSession {
  private long swigCPtr;

  protected CallSession(long cPtr, boolean cMemoryOwn) {
    super(tinyWRAPJNI.SWIGCallSessionUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CallSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      tinyWRAPJNI.delete_CallSession(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public CallSession(SipStack Stack) {
    this(tinyWRAPJNI.new_CallSession(SipStack.getCPtr(Stack), Stack), true);
  }

  public boolean CallAudio(String remoteUri) {
    return tinyWRAPJNI.CallSession_CallAudio(swigCPtr, this, remoteUri);
  }

  public boolean CallAudioVideo(String remoteUri) {
    return tinyWRAPJNI.CallSession_CallAudioVideo(swigCPtr, this, remoteUri);
  }

  public boolean CallVideo(String remoteUri) {
    return tinyWRAPJNI.CallSession_CallVideo(swigCPtr, this, remoteUri);
  }

  public boolean Hangup() {
    return tinyWRAPJNI.CallSession_Hangup(swigCPtr, this);
  }

}
