/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class SipDebugCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SipDebugCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SipDebugCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      tinyWRAPJNI.delete_SipDebugCallback(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    tinyWRAPJNI.SipDebugCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    tinyWRAPJNI.SipDebugCallback_change_ownership(this, swigCPtr, true);
  }

  public SipDebugCallback() {
    this(tinyWRAPJNI.new_SipDebugCallback(), true);
    tinyWRAPJNI.SipDebugCallback_director_connect(this, swigCPtr, swigCMemOwn, false);
  }

  public int OnDebugInfo(String message) {
    return (getClass() == SipDebugCallback.class) ? tinyWRAPJNI.SipDebugCallback_OnDebugInfo(swigCPtr, this, message) : tinyWRAPJNI.SipDebugCallback_OnDebugInfoSwigExplicitSipDebugCallback(swigCPtr, this, message);
  }

  public int OnDebugWarn(String message) {
    return (getClass() == SipDebugCallback.class) ? tinyWRAPJNI.SipDebugCallback_OnDebugWarn(swigCPtr, this, message) : tinyWRAPJNI.SipDebugCallback_OnDebugWarnSwigExplicitSipDebugCallback(swigCPtr, this, message);
  }

  public int OnDebugError(String message) {
    return (getClass() == SipDebugCallback.class) ? tinyWRAPJNI.SipDebugCallback_OnDebugError(swigCPtr, this, message) : tinyWRAPJNI.SipDebugCallback_OnDebugErrorSwigExplicitSipDebugCallback(swigCPtr, this, message);
  }

  public int OnDebugFatal(String message) {
    return (getClass() == SipDebugCallback.class) ? tinyWRAPJNI.SipDebugCallback_OnDebugFatal(swigCPtr, this, message) : tinyWRAPJNI.SipDebugCallback_OnDebugFatalSwigExplicitSipDebugCallback(swigCPtr, this, message);
  }

}
