/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : tsip_transac_ict.sm
 */

#ifndef _H_TSIP_TRANSAC_ICT_SM
#define _H_TSIP_TRANSAC_ICT_SM

#include <statemap.h>


struct tsip_transac_ict;
struct tsip_transac_ictContext;

struct tsip_transac_ictState
{


    void(*Default)(struct tsip_transac_ictContext*);

    STATE_MEMBERS
};

extern const struct tsip_transac_ictState tsip_transac_ict_Started;

struct tsip_transac_ictContext
{
    FSM_MEMBERS(tsip_transac_ict)
    struct tsip_transac_ict *_owner;
};

extern void tsip_transac_ictContext_Init(struct tsip_transac_ictContext*, struct tsip_transac_ict*);

#endif

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
