/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : tsip_transac_nist.sm
 */

#ifndef _H_TSIP_TRANSAC_NIST_SM
#define _H_TSIP_TRANSAC_NIST_SM

#include <statemap.h>


struct tsip_transac_nist;
struct tsip_transac_nistContext;

struct tsip_transac_nistState
{
    void(*Entry)(struct tsip_transac_nistContext*);

    void(*sm_recv_request)(struct tsip_transac_nistContext*, const tsip_request_t*);
    void(*sm_send_1xx)(struct tsip_transac_nistContext*, const tsip_request_t*);
    void(*sm_send_200_to_699)(struct tsip_transac_nistContext*, const tsip_request_t*);
    void(*sm_timerJ)(struct tsip_transac_nistContext*);
    void(*sm_transportError)(struct tsip_transac_nistContext*);

    void(*Default)(struct tsip_transac_nistContext*);

    STATE_MEMBERS
};

extern const struct tsip_transac_nistState tsip_transac_nist_Started;
extern const struct tsip_transac_nistState tsip_transac_nist_Trying;
extern const struct tsip_transac_nistState tsip_transac_nist_Proceeding;
extern const struct tsip_transac_nistState tsip_transac_nist_Completed;
extern const struct tsip_transac_nistState tsip_transac_nist_Terminated;

struct tsip_transac_nistContext
{
    FSM_MEMBERS(tsip_transac_nist)
    struct tsip_transac_nist *_owner;
};

extern void tsip_transac_nistContext_Init(struct tsip_transac_nistContext*, struct tsip_transac_nist*);
extern void tsip_transac_nistContext_EnterStartState(struct tsip_transac_nistContext*);
extern void tsip_transac_nistContext_sm_recv_request(struct tsip_transac_nistContext*, const tsip_request_t*);
extern void tsip_transac_nistContext_sm_send_1xx(struct tsip_transac_nistContext*, const tsip_request_t*);
extern void tsip_transac_nistContext_sm_send_200_to_699(struct tsip_transac_nistContext*, const tsip_request_t*);
extern void tsip_transac_nistContext_sm_timerJ(struct tsip_transac_nistContext*);
extern void tsip_transac_nistContext_sm_transportError(struct tsip_transac_nistContext*);

#endif

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
