/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : tsip_dialog_register.sm
 */

#ifndef _H_TSIP_DIALOG_REGISTER_SM
#define _H_TSIP_DIALOG_REGISTER_SM

#include <statemap.h>


struct tsip_dialog_register;
struct tsip_dialog_registerContext;

struct tsip_dialog_registerState
{

    void(*sm_1xx)(struct tsip_dialog_registerContext*, const tsip_message_t*);
    void(*sm_2xx)(struct tsip_dialog_registerContext*, int, const tsip_message_t*);
    void(*sm_300_to_699)(struct tsip_dialog_registerContext*, const tsip_message_t*);
    void(*sm_401_407_421_494)(struct tsip_dialog_registerContext*, int, const tsip_message_t*);
    void(*sm_423)(struct tsip_dialog_registerContext*, const tsip_message_t*);
    void(*sm_cancel)(struct tsip_dialog_registerContext*);
    void(*sm_refresh)(struct tsip_dialog_registerContext*, tsk_timer_id_t);
    void(*sm_send)(struct tsip_dialog_registerContext*);
    void(*sm_transportError)(struct tsip_dialog_registerContext*);
    void(*sm_unregister)(struct tsip_dialog_registerContext*);

    void(*Default)(struct tsip_dialog_registerContext*);

    STATE_MEMBERS
};

extern const struct tsip_dialog_registerState tsip_dialog_register_Started;
extern const struct tsip_dialog_registerState tsip_dialog_register_Trying;
extern const struct tsip_dialog_registerState tsip_dialog_register_Connected;
extern const struct tsip_dialog_registerState tsip_dialog_register_Terminated;

struct tsip_dialog_registerContext
{
    FSM_MEMBERS(tsip_dialog_register)
    struct tsip_dialog_register *_owner;
};

extern void tsip_dialog_registerContext_Init(struct tsip_dialog_registerContext*, struct tsip_dialog_register*);
extern void tsip_dialog_registerContext_sm_1xx(struct tsip_dialog_registerContext*, const tsip_message_t*);
extern void tsip_dialog_registerContext_sm_2xx(struct tsip_dialog_registerContext*, int, const tsip_message_t*);
extern void tsip_dialog_registerContext_sm_300_to_699(struct tsip_dialog_registerContext*, const tsip_message_t*);
extern void tsip_dialog_registerContext_sm_401_407_421_494(struct tsip_dialog_registerContext*, int, const tsip_message_t*);
extern void tsip_dialog_registerContext_sm_423(struct tsip_dialog_registerContext*, const tsip_message_t*);
extern void tsip_dialog_registerContext_sm_cancel(struct tsip_dialog_registerContext*);
extern void tsip_dialog_registerContext_sm_refresh(struct tsip_dialog_registerContext*, tsk_timer_id_t);
extern void tsip_dialog_registerContext_sm_send(struct tsip_dialog_registerContext*);
extern void tsip_dialog_registerContext_sm_transportError(struct tsip_dialog_registerContext*);
extern void tsip_dialog_registerContext_sm_unregister(struct tsip_dialog_registerContext*);

#endif

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
