./configure \
--build=mingw32 \
--enable-nonblocking \
--enable-http \
--enable-ipv6 \
--disable-thread \
--disable-cookies \
--disable-ftp \
--disable-file \
--disable-ldap \
--disable-gopher \
--disable-dict \
--disable-telnet \
--disable-tftp \
--disable-manual \
--disable-ares \
--disable-verbose \
--disable-sspi \
--disable-debug \
--disable-cookies \
--without-ssl \
--without-libssh2 \
--without-ca-bundle

