/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class RegistrationSession extends SipSession {
  private long swigCPtr;

  protected RegistrationSession(long cPtr, boolean cMemoryOwn) {
    super(tinyWRAPJNI.SWIGRegistrationSessionUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RegistrationSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tinyWRAPJNI.delete_RegistrationSession(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RegistrationSession(SipStack Stack) {
    this(tinyWRAPJNI.new_RegistrationSession(SipStack.getCPtr(Stack), Stack), true);
  }

  public boolean Register() {
    return tinyWRAPJNI.RegistrationSession_Register(swigCPtr, this);
  }

  public boolean UnRegister() {
    return tinyWRAPJNI.RegistrationSession_UnRegister(swigCPtr, this);
  }

}
