/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public class RPData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RPData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RPData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      tinyWRAPJNI.delete_RPData(swigCPtr);
    }
    swigCPtr = 0;
  }

  public RPData() {
    this(tinyWRAPJNI.new_RPData(), true);
  }

  public twrap_rpdata_type_t getType() {
    return twrap_rpdata_type_t.swigToEnum(tinyWRAPJNI.RPData_getType(swigCPtr, this));
  }

  public long getPayloadLength() {
    return tinyWRAPJNI.RPData_getPayloadLength(swigCPtr, this);
  }

  public long getPayload(java.nio.ByteBuffer output, long maxsize) {
    return tinyWRAPJNI.RPData_getPayload(swigCPtr, this, output, maxsize);
  }

}
