/*
 * PLEASE NOTE: 
 * 
 * This file is automatically generated by tag_dll.awk.
 * It contains tag_typedef_t for tag references.
 * 
 * Do not, repeat, do not edit this file. Edit 'tport_tag.c' instead.
 * 
 */

#include "config.h"

#include <sofia-sip/su_tag_class.h>

#if defined _WIN32 || defined HAVE_OPEN_C
#define EXPORT __declspec(dllexport)
#else
#define EXPORT
#endif


#undef TAG_NAMESPACE
#define TAG_NAMESPACE "tp"

extern tag_typedef_t tptag_ident;
EXPORT tag_typedef_t tptag_ident_ref = 
  REFTAG_TYPEDEF(tptag_ident);
extern tag_typedef_t tptag_reuse;
EXPORT tag_typedef_t tptag_reuse_ref = 
  REFTAG_TYPEDEF(tptag_reuse);
extern tag_typedef_t tptag_fresh;
EXPORT tag_typedef_t tptag_fresh_ref = 
  REFTAG_TYPEDEF(tptag_fresh);
extern tag_typedef_t tptag_server;
EXPORT tag_typedef_t tptag_server_ref = 
  REFTAG_TYPEDEF(tptag_server);
extern tag_typedef_t tptag_public;
EXPORT tag_typedef_t tptag_public_ref = 
  REFTAG_TYPEDEF(tptag_public);
extern tag_typedef_t tptag_mtu;
EXPORT tag_typedef_t tptag_mtu_ref = 
  REFTAG_TYPEDEF(tptag_mtu);
extern tag_typedef_t tptag_connect;
EXPORT tag_typedef_t tptag_connect_ref = 
  REFTAG_TYPEDEF(tptag_connect);
extern tag_typedef_t tptag_sdwn_error;
EXPORT tag_typedef_t tptag_sdwn_error_ref = 
  REFTAG_TYPEDEF(tptag_sdwn_error);
extern tag_typedef_t tptag_sdwn_after;
EXPORT tag_typedef_t tptag_sdwn_after_ref = 
  REFTAG_TYPEDEF(tptag_sdwn_after);
extern tag_typedef_t tptag_close_after;
EXPORT tag_typedef_t tptag_close_after_ref = 
  REFTAG_TYPEDEF(tptag_close_after);
extern tag_typedef_t tptag_idle;
EXPORT tag_typedef_t tptag_idle_ref = 
  REFTAG_TYPEDEF(tptag_idle);
extern tag_typedef_t tptag_timeout;
EXPORT tag_typedef_t tptag_timeout_ref = 
  REFTAG_TYPEDEF(tptag_timeout);
extern tag_typedef_t tptag_keepalive;
EXPORT tag_typedef_t tptag_keepalive_ref = 
  REFTAG_TYPEDEF(tptag_keepalive);
extern tag_typedef_t tptag_pingpong;
EXPORT tag_typedef_t tptag_pingpong_ref = 
  REFTAG_TYPEDEF(tptag_pingpong);
extern tag_typedef_t tptag_pong2ping;
EXPORT tag_typedef_t tptag_pong2ping_ref = 
  REFTAG_TYPEDEF(tptag_pong2ping);
extern tag_typedef_t tptag_sigcomp_lifetime;
EXPORT tag_typedef_t tptag_sigcomp_lifetime_ref = 
  REFTAG_TYPEDEF(tptag_sigcomp_lifetime);
extern tag_typedef_t tptag_certificate;
EXPORT tag_typedef_t tptag_certificate_ref = 
  REFTAG_TYPEDEF(tptag_certificate);
extern tag_typedef_t tptag_compartment;
EXPORT tag_typedef_t tptag_compartment_ref = 
  REFTAG_TYPEDEF(tptag_compartment);
extern tag_typedef_t tptag_tls_version;
EXPORT tag_typedef_t tptag_tls_version_ref = 
  REFTAG_TYPEDEF(tptag_tls_version);
extern tag_typedef_t tptag_tls_verify_peer;
EXPORT tag_typedef_t tptag_tls_verify_peer_ref = 
  REFTAG_TYPEDEF(tptag_tls_verify_peer);
extern tag_typedef_t tptag_queuesize;
EXPORT tag_typedef_t tptag_queuesize_ref = 
  REFTAG_TYPEDEF(tptag_queuesize);
extern tag_typedef_t tptag_debug_drop;
EXPORT tag_typedef_t tptag_debug_drop_ref = 
  REFTAG_TYPEDEF(tptag_debug_drop);
extern tag_typedef_t tptag_udp_rmem;
EXPORT tag_typedef_t tptag_udp_rmem_ref = 
  REFTAG_TYPEDEF(tptag_udp_rmem);
extern tag_typedef_t tptag_udp_wmem;
EXPORT tag_typedef_t tptag_udp_wmem_ref = 
  REFTAG_TYPEDEF(tptag_udp_wmem);
extern tag_typedef_t tptag_thrpsize;
EXPORT tag_typedef_t tptag_thrpsize_ref = 
  REFTAG_TYPEDEF(tptag_thrpsize);
extern tag_typedef_t tptag_thrprqsize;
EXPORT tag_typedef_t tptag_thrprqsize_ref = 
  REFTAG_TYPEDEF(tptag_thrprqsize);
extern tag_typedef_t tptag_http_connect;
EXPORT tag_typedef_t tptag_http_connect_ref = 
  REFTAG_TYPEDEF(tptag_http_connect);
extern tag_typedef_t tptag_stun_server;
EXPORT tag_typedef_t tptag_stun_server_ref = 
  REFTAG_TYPEDEF(tptag_stun_server);
extern tag_typedef_t tptag_tos;
EXPORT tag_typedef_t tptag_tos_ref = 
  REFTAG_TYPEDEF(tptag_tos);
extern tag_typedef_t tptag_log;
EXPORT tag_typedef_t tptag_log_ref = 
  REFTAG_TYPEDEF(tptag_log);
extern tag_typedef_t tptag_dump;
EXPORT tag_typedef_t tptag_dump_ref = 
  REFTAG_TYPEDEF(tptag_dump);
extern tag_typedef_t tptag_trusted;
EXPORT tag_typedef_t tptag_trusted_ref = 
  REFTAG_TYPEDEF(tptag_trusted);
