/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.tinyWRAP {

using System;
using System.Runtime.InteropServices;

public class ProxyVideoConsumerCallback : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ProxyVideoConsumerCallback(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ProxyVideoConsumerCallback obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ProxyVideoConsumerCallback() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          tinyWRAPPINVOKE.delete_ProxyVideoConsumerCallback(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public ProxyVideoConsumerCallback() : this(tinyWRAPPINVOKE.new_ProxyVideoConsumerCallback(), true) {
    SwigDirectorConnect();
  }

  public virtual int prepare(int nWidth, int nHeight, int nFps) {
    int ret = (SwigDerivedClassHasMethod("prepare", swigMethodTypes0) ? tinyWRAPPINVOKE.ProxyVideoConsumerCallback_prepareSwigExplicitProxyVideoConsumerCallback(swigCPtr, nWidth, nHeight, nFps) : tinyWRAPPINVOKE.ProxyVideoConsumerCallback_prepare(swigCPtr, nWidth, nHeight, nFps));
    return ret;
  }

  public virtual int consume(ProxyVideoFrame frame) {
    int ret = (SwigDerivedClassHasMethod("consume", swigMethodTypes1) ? tinyWRAPPINVOKE.ProxyVideoConsumerCallback_consumeSwigExplicitProxyVideoConsumerCallback(swigCPtr, ProxyVideoFrame.getCPtr(frame)) : tinyWRAPPINVOKE.ProxyVideoConsumerCallback_consume(swigCPtr, ProxyVideoFrame.getCPtr(frame)));
    return ret;
  }

  public virtual int bufferCopied(uint nCopiedSize, uint nAvailableSize) {
    int ret = (SwigDerivedClassHasMethod("bufferCopied", swigMethodTypes2) ? tinyWRAPPINVOKE.ProxyVideoConsumerCallback_bufferCopiedSwigExplicitProxyVideoConsumerCallback(swigCPtr, nCopiedSize, nAvailableSize) : tinyWRAPPINVOKE.ProxyVideoConsumerCallback_bufferCopied(swigCPtr, nCopiedSize, nAvailableSize));
    return ret;
  }

  public virtual int start() {
    int ret = (SwigDerivedClassHasMethod("start", swigMethodTypes3) ? tinyWRAPPINVOKE.ProxyVideoConsumerCallback_startSwigExplicitProxyVideoConsumerCallback(swigCPtr) : tinyWRAPPINVOKE.ProxyVideoConsumerCallback_start(swigCPtr));
    return ret;
  }

  public virtual int pause() {
    int ret = (SwigDerivedClassHasMethod("pause", swigMethodTypes4) ? tinyWRAPPINVOKE.ProxyVideoConsumerCallback_pauseSwigExplicitProxyVideoConsumerCallback(swigCPtr) : tinyWRAPPINVOKE.ProxyVideoConsumerCallback_pause(swigCPtr));
    return ret;
  }

  public virtual int stop() {
    int ret = (SwigDerivedClassHasMethod("stop", swigMethodTypes5) ? tinyWRAPPINVOKE.ProxyVideoConsumerCallback_stopSwigExplicitProxyVideoConsumerCallback(swigCPtr) : tinyWRAPPINVOKE.ProxyVideoConsumerCallback_stop(swigCPtr));
    return ret;
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("prepare", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateProxyVideoConsumerCallback_0(SwigDirectorprepare);
    if (SwigDerivedClassHasMethod("consume", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateProxyVideoConsumerCallback_1(SwigDirectorconsume);
    if (SwigDerivedClassHasMethod("bufferCopied", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateProxyVideoConsumerCallback_2(SwigDirectorbufferCopied);
    if (SwigDerivedClassHasMethod("start", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateProxyVideoConsumerCallback_3(SwigDirectorstart);
    if (SwigDerivedClassHasMethod("pause", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateProxyVideoConsumerCallback_4(SwigDirectorpause);
    if (SwigDerivedClassHasMethod("stop", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateProxyVideoConsumerCallback_5(SwigDirectorstop);
    tinyWRAPPINVOKE.ProxyVideoConsumerCallback_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5);
  }

  private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes) {
    System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(ProxyVideoConsumerCallback));
    return hasDerivedMethod;
  }

  private int SwigDirectorprepare(int nWidth, int nHeight, int nFps) {
    return prepare(nWidth, nHeight, nFps);
  }

  private int SwigDirectorconsume(IntPtr frame) {
    return consume((frame == IntPtr.Zero) ? null : new ProxyVideoFrame(frame, false));
  }

  private int SwigDirectorbufferCopied(uint nCopiedSize, uint nAvailableSize) {
    return bufferCopied(nCopiedSize, nAvailableSize);
  }

  private int SwigDirectorstart() {
    return start();
  }

  private int SwigDirectorpause() {
    return pause();
  }

  private int SwigDirectorstop() {
    return stop();
  }

  public delegate int SwigDelegateProxyVideoConsumerCallback_0(int nWidth, int nHeight, int nFps);
  public delegate int SwigDelegateProxyVideoConsumerCallback_1(IntPtr frame);
  public delegate int SwigDelegateProxyVideoConsumerCallback_2(uint nCopiedSize, uint nAvailableSize);
  public delegate int SwigDelegateProxyVideoConsumerCallback_3();
  public delegate int SwigDelegateProxyVideoConsumerCallback_4();
  public delegate int SwigDelegateProxyVideoConsumerCallback_5();

  private SwigDelegateProxyVideoConsumerCallback_0 swigDelegate0;
  private SwigDelegateProxyVideoConsumerCallback_1 swigDelegate1;
  private SwigDelegateProxyVideoConsumerCallback_2 swigDelegate2;
  private SwigDelegateProxyVideoConsumerCallback_3 swigDelegate3;
  private SwigDelegateProxyVideoConsumerCallback_4 swigDelegate4;
  private SwigDelegateProxyVideoConsumerCallback_5 swigDelegate5;

  private static Type[] swigMethodTypes0 = new Type[] { typeof(int), typeof(int), typeof(int) };
  private static Type[] swigMethodTypes1 = new Type[] { typeof(ProxyVideoFrame) };
  private static Type[] swigMethodTypes2 = new Type[] { typeof(uint), typeof(uint) };
  private static Type[] swigMethodTypes3 = new Type[] {  };
  private static Type[] swigMethodTypes4 = new Type[] {  };
  private static Type[] swigMethodTypes5 = new Type[] {  };
}

}
