/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.tinyWRAP {

public enum tmedia_mode_t {
  tmedia_mode_none,
  tmedia_mode_optional,
  tmedia_mode_mandatory
}

}
