/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.tinyWRAP {

public enum tmedia_chroma_t {
  tmedia_chroma_none = 0,
  tmedia_chroma_rgb24,
  tmedia_chroma_bgr24,
  tmedia_chroma_rgb32,
  tmedia_chroma_rgb565le,
  tmedia_chroma_rgb565be,
  tmedia_chroma_nv12,
  tmedia_chroma_nv21,
  tmedia_chroma_yuv422p,
  tmedia_chroma_uyvy422,
  tmedia_chroma_yuv420p
}

}
