/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.tinyWRAP {

public enum tsip_request_type_t {
  tsip_NONE = 0,
  tsip_ACK,
  tsip_BYE,
  tsip_CANCEL,
  tsip_INVITE,
  tsip_OPTIONS,
  tsip_REGISTER,
  tsip_SUBSCRIBE,
  tsip_NOTIFY,
  tsip_REFER,
  tsip_INFO,
  tsip_UPDATE,
  tsip_MESSAGE,
  tsip_PUBLISH,
  tsip_PRACK
}

}
