/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.tinyWRAP {

public enum tsip_invite_event_type_t {
  tsip_i_newcall,
  tsip_i_request,
  tsip_ao_request,
  tsip_o_ect_ok,
  tsip_o_ect_nok,
  tsip_i_ect,
  tsip_m_early_media,
  tsip_m_local_hold_ok,
  tsip_m_local_hold_nok,
  tsip_m_local_resume_ok,
  tsip_m_local_resume_nok,
  tsip_m_remote_hold,
  tsip_m_remote_resume
}

}
