/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.tinyWRAP {

public enum tsip_stack_mode_t {
  tsip_stack_mode_ua,
  tsip_stack_mode_p2p,
  tsip_stack_mode_mediaproxy,
  tsip_stack_mode_mcu
}

}
