/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.tinyWRAP {

public enum twrap_media_type_t {
  twrap_media_none = 0x00,
  twrap_media_audio = 0x01,
  twrap_media_video = 0x02,
  twrap_media_msrp = 0x04,
  twrap_media_t140 = 0x08,
  twrap_media_bfcp = 0x10,
  twrap_media_bfcp_audio = 0x30,
  twrap_media_bfcp_video = 0x50,
  twrap_media_audiovideo = 0x03,
  twrap_media_audio_video = twrap_media_audiovideo
}

}
