/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.ipsecWRAP {

public enum tipsec_error_t {
  tipsec_error_success = 0,
  tipsec_error_invalid_param,
  tipsec_error_invalid_state,
  tipsec_error_access_violation,
  tipsec_error_permission_denied,
  tipsec_error_outofmemory,
  tipsec_error_outofbound,
  tipsec_error_notfound,
  tipsec_error_notimplemented,
  tipsec_error_sys
}

}
