#ifndef _H_SM_DIALOG_OPTIONS_SM
#define _H_SM_DIALOG_OPTIONS_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : sm_dialog_options.sm
 */


#define SMC_USES_IOSTREAMS

#define SMC_NO_EXCEPTIONS

#include <statemap.h>

namespace dgo
{
    // Forward declarations.
    class map_dialog_options;
    class map_dialog_options_Initialized;
    class map_dialog_options_Default;
    class sip_dialog_optionsState;
    class sip_dialog_optionsContext;
    class sip_dialog_options;

    class sip_dialog_optionsState :
        public statemap::State
    {
    public:

        sip_dialog_optionsState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(sip_dialog_optionsContext&) {};
        virtual void Exit(sip_dialog_optionsContext&) {};


    protected:

        virtual void Default(sip_dialog_optionsContext& context);
    };

    class map_dialog_options
    {
    public:

        static map_dialog_options_Initialized Initialized;
    };

    class map_dialog_options_Default :
        public sip_dialog_optionsState
    {
    public:

        map_dialog_options_Default(const char *name, int stateId)
        : sip_dialog_optionsState(name, stateId)
        {};

    };

    class map_dialog_options_Initialized :
        public map_dialog_options_Default
    {
    public:
        map_dialog_options_Initialized(const char *name, int stateId)
        : map_dialog_options_Default(name, stateId)
        {};

    };

    class sip_dialog_optionsContext :
        public statemap::FSMContext
    {
    public:

        sip_dialog_optionsContext(sip_dialog_options& owner)
        : FSMContext(map_dialog_options::Initialized),
          _owner(owner)
        {};

        sip_dialog_optionsContext(sip_dialog_options& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        sip_dialog_options& getOwner() const
        {
            return (_owner);
        };

        sip_dialog_optionsState& getState() const
        {
            if (_state == NULL)
            {
                assert(1 == 0);
            }

            return (dynamic_cast<sip_dialog_optionsState&>(*_state));
        };

    private:

        sip_dialog_options& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_SM_DIALOG_OPTIONS_SM
