#ifndef _H_SM_DIALOG_REGISTER_SM
#define _H_SM_DIALOG_REGISTER_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : sm_dialog_register.sm
 */


#define SMC_USES_IOSTREAMS

#define SMC_NO_EXCEPTIONS

#include <statemap.h>

namespace dgo
{
    // Forward declarations.
    class map_dialog_register;
    class map_dialog_register_Initialized;
    class map_dialog_register_Default;
    class sip_dialog_registerState;
    class sip_dialog_registerContext;
    class sip_dialog_register;

    class sip_dialog_registerState :
        public statemap::State
    {
    public:

        sip_dialog_registerState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(sip_dialog_registerContext&) {};
        virtual void Exit(sip_dialog_registerContext&) {};


    protected:

        virtual void Default(sip_dialog_registerContext& context);
    };

    class map_dialog_register
    {
    public:

        static map_dialog_register_Initialized Initialized;
    };

    class map_dialog_register_Default :
        public sip_dialog_registerState
    {
    public:

        map_dialog_register_Default(const char *name, int stateId)
        : sip_dialog_registerState(name, stateId)
        {};

    };

    class map_dialog_register_Initialized :
        public map_dialog_register_Default
    {
    public:
        map_dialog_register_Initialized(const char *name, int stateId)
        : map_dialog_register_Default(name, stateId)
        {};

    };

    class sip_dialog_registerContext :
        public statemap::FSMContext
    {
    public:

        sip_dialog_registerContext(sip_dialog_register& owner)
        : FSMContext(map_dialog_register::Initialized),
          _owner(owner)
        {};

        sip_dialog_registerContext(sip_dialog_register& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        sip_dialog_register& getOwner() const
        {
            return (_owner);
        };

        sip_dialog_registerState& getState() const
        {
            if (_state == NULL)
            {
                assert(1 == 0);
            }

            return (dynamic_cast<sip_dialog_registerState&>(*_state));
        };

    private:

        sip_dialog_register& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_SM_DIALOG_REGISTER_SM
