/*
 * PLEASE NOTE: 
 * 
 * This file is automatically generated by tag_dll.awk.
 * It contains tag_typedef_t for tag references.
 * 
 * Do not, repeat, do not edit this file. Edit 'url_tag.c' instead.
 * 
 */

#include "config.h"

#include <sofia-sip/su_tag_class.h>

#if defined _WIN32 || defined HAVE_OPEN_C
#define EXPORT __declspec(dllexport)
#else
#define EXPORT
#endif


#undef TAG_NAMESPACE
#define TAG_NAMESPACE "url"

extern tag_typedef_t urltag_url;
EXPORT tag_typedef_t urltag_url_ref = 
  REFTAG_TYPEDEF(urltag_url);
