.TH "addrinfo" 1 "8 Dec 2008" "Version 1.12.10" "sofia-sip-utils" \" -*- nroff -*-
.ad l
.nh
.SH NAME
addrinfo \- Resolve network services 
.SH "Synopsis"
.PP
\fCaddrinfo [-pcn46] service-name host\fP
.SH "Description"
.PP
The \fIaddrinfo\fP utility will use su_getaddrinfo() to resolve the network services and print resolved names. See sect 6.1 of RFC3493 and the getaddrinfo(3) manual page of POSIX 1003.1g, for more information.
.SH "Options"
.PP
The \fIaddrinfo\fP utility accepts following ccommand line options: 
.IP "\fB-p \fP" 1c
use passive open. 
.IP "\fB-c \fP" 1c
get canonic name. 
.IP "\fB-n \fP" 1c
use numeric host names. 
.IP "\fB-4 \fP" 1c
IPv4 only. 
.IP "\fB-6 \fP" 1c
IPv6 only (but including mapped IPv4 addresses). 
.PP
.SH "Reporting Bugs"
.PP
Report bugs to <sofia-sip-devel@lists.sourceforge.net>.
.SH "Author"
.PP
Written by Pekka Pessi <pekka -dot pessi -at- nokia -dot- com>
.SH "Copyright"
.PP
Copyright (C) 2005,2007 Nokia Corporation.
.PP
This program is free software; see the source for copying conditions. There is \fBNO\fP warranty; not even for \fBMERCHANTABILITY\fP or \fBFITNESS FOR A PARTICULAR PURPOSE\fP. 
