.TH "localinfo" 1 "8 Dec 2008" "Version 1.12.10" "sofia-sip-utils" \" -*- nroff -*-
.ad l
.nh
.SH NAME
localinfo \- list local network addresses 
.SH "Synopsis"
.PP
\fClocalinfo [-imdn46gslh] [domainname]\fP
.SH "Description"
.PP
The \fIlocalinfo\fP utility will obtain the local network addresses and print them.
.SH "Options"
.PP
The \fIlocalinfo\fP utility accepts following command line options: 
.IP "\fB-i \fP" 1c
include interface name. 
.IP "\fB-m \fP" 1c
map IPv4 addresses. 
.IP "\fB-d \fP" 1c
require a reverse DNS entry. 
.IP "\fB-n \fP" 1c
use numeric host names. 
.IP "\fB-4 \fP" 1c
IPv4 only. 
.IP "\fB-6 \fP" 1c
IPv6 only (but including mapped IPv4 addresses). 
.IP "\fB-g \fP" 1c
Global addresses. 
.IP "\fB-s \fP" 1c
Site-level addresses. 
.IP "\fB-l \fP" 1c
Link-level addresses. 
.IP "\fB-h \fP" 1c
Host-internal addresses. 
.PP
.SH "Examples"
.PP
You want to find out local IPv6 addresses: 
.PP
.nf
 $ localinfo -6

.fi
.PP
 You want to find out to link-local addresses 
.PP
.nf
 $ localinfo -l -n

.fi
.PP
.SH "Reporting Bugs"
.PP
Report bugs to <sofia-sip-devel@lists.sourceforge.net>.
.SH "Author"
.PP
Written by Pekka Pessi <pekka -dot pessi -at- nokia -dot- com>
.SH "Copyright"
.PP
Copyright (C) 2005 Nokia Corporation.
.PP
This program is free software; see the source for copying conditions. There is \fBNO\fP warranty; not even for \fBMERCHANTABILITY\fP or \fBFITNESS FOR A PARTICULAR PURPOSE\fP. 
