/*
 * PLEASE NOTE: 
 * 
 * This file is automatically generated by tag_dll.awk.
 * It contains tag_typedef_t for tag references.
 * 
 * Do not, repeat, do not edit this file. Edit 'http_tag.c' instead.
 * 
 */

#include "config.h"

#include <sofia-sip/su_tag_class.h>

#if defined _WIN32 || defined HAVE_OPEN_C
#define EXPORT __declspec(dllexport)
#else
#define EXPORT
#endif


#undef TAG_NAMESPACE
#define TAG_NAMESPACE "http"

extern tag_typedef_t httptag_http;
EXPORT tag_typedef_t httptag_http_ref = 
  REFTAG_TYPEDEF(httptag_http);
extern tag_typedef_t httptag_version;
EXPORT tag_typedef_t httptag_version_ref = 
  REFTAG_TYPEDEF(httptag_version);
extern tag_typedef_t httptag_header;
EXPORT tag_typedef_t httptag_header_ref = 
  REFTAG_TYPEDEF(httptag_header);
extern tag_typedef_t httptag_header_str;
EXPORT tag_typedef_t httptag_header_str_ref = 
  REFTAG_TYPEDEF(httptag_header_str);
extern tag_typedef_t httptag_request;
EXPORT tag_typedef_t httptag_request_ref = 
  REFTAG_TYPEDEF(httptag_request);
extern tag_typedef_t httptag_request_str;
EXPORT tag_typedef_t httptag_request_str_ref = 
  REFTAG_TYPEDEF(httptag_request_str);
extern tag_typedef_t httptag_status;
EXPORT tag_typedef_t httptag_status_ref = 
  REFTAG_TYPEDEF(httptag_status);
extern tag_typedef_t httptag_status_str;
EXPORT tag_typedef_t httptag_status_str_ref = 
  REFTAG_TYPEDEF(httptag_status_str);
extern tag_typedef_t httptag_accept;
EXPORT tag_typedef_t httptag_accept_ref = 
  REFTAG_TYPEDEF(httptag_accept);
extern tag_typedef_t httptag_accept_str;
EXPORT tag_typedef_t httptag_accept_str_ref = 
  REFTAG_TYPEDEF(httptag_accept_str);
extern tag_typedef_t httptag_accept_charset;
EXPORT tag_typedef_t httptag_accept_charset_ref = 
  REFTAG_TYPEDEF(httptag_accept_charset);
extern tag_typedef_t httptag_accept_charset_str;
EXPORT tag_typedef_t httptag_accept_charset_str_ref = 
  REFTAG_TYPEDEF(httptag_accept_charset_str);
extern tag_typedef_t httptag_accept_encoding;
EXPORT tag_typedef_t httptag_accept_encoding_ref = 
  REFTAG_TYPEDEF(httptag_accept_encoding);
extern tag_typedef_t httptag_accept_encoding_str;
EXPORT tag_typedef_t httptag_accept_encoding_str_ref = 
  REFTAG_TYPEDEF(httptag_accept_encoding_str);
extern tag_typedef_t httptag_accept_language;
EXPORT tag_typedef_t httptag_accept_language_ref = 
  REFTAG_TYPEDEF(httptag_accept_language);
extern tag_typedef_t httptag_accept_language_str;
EXPORT tag_typedef_t httptag_accept_language_str_ref = 
  REFTAG_TYPEDEF(httptag_accept_language_str);
extern tag_typedef_t httptag_accept_ranges;
EXPORT tag_typedef_t httptag_accept_ranges_ref = 
  REFTAG_TYPEDEF(httptag_accept_ranges);
extern tag_typedef_t httptag_accept_ranges_str;
EXPORT tag_typedef_t httptag_accept_ranges_str_ref = 
  REFTAG_TYPEDEF(httptag_accept_ranges_str);
extern tag_typedef_t httptag_allow;
EXPORT tag_typedef_t httptag_allow_ref = 
  REFTAG_TYPEDEF(httptag_allow);
extern tag_typedef_t httptag_allow_str;
EXPORT tag_typedef_t httptag_allow_str_ref = 
  REFTAG_TYPEDEF(httptag_allow_str);
extern tag_typedef_t httptag_authentication_info;
EXPORT tag_typedef_t httptag_authentication_info_ref = 
  REFTAG_TYPEDEF(httptag_authentication_info);
extern tag_typedef_t httptag_authentication_info_str;
EXPORT tag_typedef_t httptag_authentication_info_str_ref = 
  REFTAG_TYPEDEF(httptag_authentication_info_str);
extern tag_typedef_t httptag_authorization;
EXPORT tag_typedef_t httptag_authorization_ref = 
  REFTAG_TYPEDEF(httptag_authorization);
extern tag_typedef_t httptag_authorization_str;
EXPORT tag_typedef_t httptag_authorization_str_ref = 
  REFTAG_TYPEDEF(httptag_authorization_str);
extern tag_typedef_t httptag_age;
EXPORT tag_typedef_t httptag_age_ref = 
  REFTAG_TYPEDEF(httptag_age);
extern tag_typedef_t httptag_age_str;
EXPORT tag_typedef_t httptag_age_str_ref = 
  REFTAG_TYPEDEF(httptag_age_str);
extern tag_typedef_t httptag_cache_control;
EXPORT tag_typedef_t httptag_cache_control_ref = 
  REFTAG_TYPEDEF(httptag_cache_control);
extern tag_typedef_t httptag_cache_control_str;
EXPORT tag_typedef_t httptag_cache_control_str_ref = 
  REFTAG_TYPEDEF(httptag_cache_control_str);
extern tag_typedef_t httptag_connection;
EXPORT tag_typedef_t httptag_connection_ref = 
  REFTAG_TYPEDEF(httptag_connection);
extern tag_typedef_t httptag_connection_str;
EXPORT tag_typedef_t httptag_connection_str_ref = 
  REFTAG_TYPEDEF(httptag_connection_str);
extern tag_typedef_t httptag_date;
EXPORT tag_typedef_t httptag_date_ref = 
  REFTAG_TYPEDEF(httptag_date);
extern tag_typedef_t httptag_date_str;
EXPORT tag_typedef_t httptag_date_str_ref = 
  REFTAG_TYPEDEF(httptag_date_str);
extern tag_typedef_t httptag_etag;
EXPORT tag_typedef_t httptag_etag_ref = 
  REFTAG_TYPEDEF(httptag_etag);
extern tag_typedef_t httptag_etag_str;
EXPORT tag_typedef_t httptag_etag_str_ref = 
  REFTAG_TYPEDEF(httptag_etag_str);
extern tag_typedef_t httptag_expect;
EXPORT tag_typedef_t httptag_expect_ref = 
  REFTAG_TYPEDEF(httptag_expect);
extern tag_typedef_t httptag_expect_str;
EXPORT tag_typedef_t httptag_expect_str_ref = 
  REFTAG_TYPEDEF(httptag_expect_str);
extern tag_typedef_t httptag_expires;
EXPORT tag_typedef_t httptag_expires_ref = 
  REFTAG_TYPEDEF(httptag_expires);
extern tag_typedef_t httptag_expires_str;
EXPORT tag_typedef_t httptag_expires_str_ref = 
  REFTAG_TYPEDEF(httptag_expires_str);
extern tag_typedef_t httptag_from;
EXPORT tag_typedef_t httptag_from_ref = 
  REFTAG_TYPEDEF(httptag_from);
extern tag_typedef_t httptag_from_str;
EXPORT tag_typedef_t httptag_from_str_ref = 
  REFTAG_TYPEDEF(httptag_from_str);
extern tag_typedef_t httptag_host;
EXPORT tag_typedef_t httptag_host_ref = 
  REFTAG_TYPEDEF(httptag_host);
extern tag_typedef_t httptag_host_str;
EXPORT tag_typedef_t httptag_host_str_ref = 
  REFTAG_TYPEDEF(httptag_host_str);
extern tag_typedef_t httptag_if_match;
EXPORT tag_typedef_t httptag_if_match_ref = 
  REFTAG_TYPEDEF(httptag_if_match);
extern tag_typedef_t httptag_if_match_str;
EXPORT tag_typedef_t httptag_if_match_str_ref = 
  REFTAG_TYPEDEF(httptag_if_match_str);
extern tag_typedef_t httptag_if_modified_since;
EXPORT tag_typedef_t httptag_if_modified_since_ref = 
  REFTAG_TYPEDEF(httptag_if_modified_since);
extern tag_typedef_t httptag_if_modified_since_str;
EXPORT tag_typedef_t httptag_if_modified_since_str_ref = 
  REFTAG_TYPEDEF(httptag_if_modified_since_str);
extern tag_typedef_t httptag_if_none_match;
EXPORT tag_typedef_t httptag_if_none_match_ref = 
  REFTAG_TYPEDEF(httptag_if_none_match);
extern tag_typedef_t httptag_if_none_match_str;
EXPORT tag_typedef_t httptag_if_none_match_str_ref = 
  REFTAG_TYPEDEF(httptag_if_none_match_str);
extern tag_typedef_t httptag_if_range;
EXPORT tag_typedef_t httptag_if_range_ref = 
  REFTAG_TYPEDEF(httptag_if_range);
extern tag_typedef_t httptag_if_range_str;
EXPORT tag_typedef_t httptag_if_range_str_ref = 
  REFTAG_TYPEDEF(httptag_if_range_str);
extern tag_typedef_t httptag_if_unmodified_since;
EXPORT tag_typedef_t httptag_if_unmodified_since_ref = 
  REFTAG_TYPEDEF(httptag_if_unmodified_since);
extern tag_typedef_t httptag_if_unmodified_since_str;
EXPORT tag_typedef_t httptag_if_unmodified_since_str_ref = 
  REFTAG_TYPEDEF(httptag_if_unmodified_since_str);
extern tag_typedef_t httptag_last_modified;
EXPORT tag_typedef_t httptag_last_modified_ref = 
  REFTAG_TYPEDEF(httptag_last_modified);
extern tag_typedef_t httptag_last_modified_str;
EXPORT tag_typedef_t httptag_last_modified_str_ref = 
  REFTAG_TYPEDEF(httptag_last_modified_str);
extern tag_typedef_t httptag_location;
EXPORT tag_typedef_t httptag_location_ref = 
  REFTAG_TYPEDEF(httptag_location);
extern tag_typedef_t httptag_location_str;
EXPORT tag_typedef_t httptag_location_str_ref = 
  REFTAG_TYPEDEF(httptag_location_str);
extern tag_typedef_t httptag_max_forwards;
EXPORT tag_typedef_t httptag_max_forwards_ref = 
  REFTAG_TYPEDEF(httptag_max_forwards);
extern tag_typedef_t httptag_max_forwards_str;
EXPORT tag_typedef_t httptag_max_forwards_str_ref = 
  REFTAG_TYPEDEF(httptag_max_forwards_str);
extern tag_typedef_t httptag_pragma;
EXPORT tag_typedef_t httptag_pragma_ref = 
  REFTAG_TYPEDEF(httptag_pragma);
extern tag_typedef_t httptag_pragma_str;
EXPORT tag_typedef_t httptag_pragma_str_ref = 
  REFTAG_TYPEDEF(httptag_pragma_str);
extern tag_typedef_t httptag_proxy_authenticate;
EXPORT tag_typedef_t httptag_proxy_authenticate_ref = 
  REFTAG_TYPEDEF(httptag_proxy_authenticate);
extern tag_typedef_t httptag_proxy_authenticate_str;
EXPORT tag_typedef_t httptag_proxy_authenticate_str_ref = 
  REFTAG_TYPEDEF(httptag_proxy_authenticate_str);
extern tag_typedef_t httptag_proxy_authorization;
EXPORT tag_typedef_t httptag_proxy_authorization_ref = 
  REFTAG_TYPEDEF(httptag_proxy_authorization);
extern tag_typedef_t httptag_proxy_authorization_str;
EXPORT tag_typedef_t httptag_proxy_authorization_str_ref = 
  REFTAG_TYPEDEF(httptag_proxy_authorization_str);
extern tag_typedef_t httptag_range;
EXPORT tag_typedef_t httptag_range_ref = 
  REFTAG_TYPEDEF(httptag_range);
extern tag_typedef_t httptag_range_str;
EXPORT tag_typedef_t httptag_range_str_ref = 
  REFTAG_TYPEDEF(httptag_range_str);
extern tag_typedef_t httptag_referer;
EXPORT tag_typedef_t httptag_referer_ref = 
  REFTAG_TYPEDEF(httptag_referer);
extern tag_typedef_t httptag_referer_str;
EXPORT tag_typedef_t httptag_referer_str_ref = 
  REFTAG_TYPEDEF(httptag_referer_str);
extern tag_typedef_t httptag_retry_after;
EXPORT tag_typedef_t httptag_retry_after_ref = 
  REFTAG_TYPEDEF(httptag_retry_after);
extern tag_typedef_t httptag_retry_after_str;
EXPORT tag_typedef_t httptag_retry_after_str_ref = 
  REFTAG_TYPEDEF(httptag_retry_after_str);
extern tag_typedef_t httptag_server;
EXPORT tag_typedef_t httptag_server_ref = 
  REFTAG_TYPEDEF(httptag_server);
extern tag_typedef_t httptag_server_str;
EXPORT tag_typedef_t httptag_server_str_ref = 
  REFTAG_TYPEDEF(httptag_server_str);
extern tag_typedef_t httptag_te;
EXPORT tag_typedef_t httptag_te_ref = 
  REFTAG_TYPEDEF(httptag_te);
extern tag_typedef_t httptag_te_str;
EXPORT tag_typedef_t httptag_te_str_ref = 
  REFTAG_TYPEDEF(httptag_te_str);
extern tag_typedef_t httptag_trailer;
EXPORT tag_typedef_t httptag_trailer_ref = 
  REFTAG_TYPEDEF(httptag_trailer);
extern tag_typedef_t httptag_trailer_str;
EXPORT tag_typedef_t httptag_trailer_str_ref = 
  REFTAG_TYPEDEF(httptag_trailer_str);
extern tag_typedef_t httptag_transfer_encoding;
EXPORT tag_typedef_t httptag_transfer_encoding_ref = 
  REFTAG_TYPEDEF(httptag_transfer_encoding);
extern tag_typedef_t httptag_transfer_encoding_str;
EXPORT tag_typedef_t httptag_transfer_encoding_str_ref = 
  REFTAG_TYPEDEF(httptag_transfer_encoding_str);
extern tag_typedef_t httptag_upgrade;
EXPORT tag_typedef_t httptag_upgrade_ref = 
  REFTAG_TYPEDEF(httptag_upgrade);
extern tag_typedef_t httptag_upgrade_str;
EXPORT tag_typedef_t httptag_upgrade_str_ref = 
  REFTAG_TYPEDEF(httptag_upgrade_str);
extern tag_typedef_t httptag_user_agent;
EXPORT tag_typedef_t httptag_user_agent_ref = 
  REFTAG_TYPEDEF(httptag_user_agent);
extern tag_typedef_t httptag_user_agent_str;
EXPORT tag_typedef_t httptag_user_agent_str_ref = 
  REFTAG_TYPEDEF(httptag_user_agent_str);
extern tag_typedef_t httptag_vary;
EXPORT tag_typedef_t httptag_vary_ref = 
  REFTAG_TYPEDEF(httptag_vary);
extern tag_typedef_t httptag_vary_str;
EXPORT tag_typedef_t httptag_vary_str_ref = 
  REFTAG_TYPEDEF(httptag_vary_str);
extern tag_typedef_t httptag_via;
EXPORT tag_typedef_t httptag_via_ref = 
  REFTAG_TYPEDEF(httptag_via);
extern tag_typedef_t httptag_via_str;
EXPORT tag_typedef_t httptag_via_str_ref = 
  REFTAG_TYPEDEF(httptag_via_str);
extern tag_typedef_t httptag_warning;
EXPORT tag_typedef_t httptag_warning_ref = 
  REFTAG_TYPEDEF(httptag_warning);
extern tag_typedef_t httptag_warning_str;
EXPORT tag_typedef_t httptag_warning_str_ref = 
  REFTAG_TYPEDEF(httptag_warning_str);
extern tag_typedef_t httptag_www_authenticate;
EXPORT tag_typedef_t httptag_www_authenticate_ref = 
  REFTAG_TYPEDEF(httptag_www_authenticate);
extern tag_typedef_t httptag_www_authenticate_str;
EXPORT tag_typedef_t httptag_www_authenticate_str_ref = 
  REFTAG_TYPEDEF(httptag_www_authenticate_str);
extern tag_typedef_t httptag_proxy_connection;
EXPORT tag_typedef_t httptag_proxy_connection_ref = 
  REFTAG_TYPEDEF(httptag_proxy_connection);
extern tag_typedef_t httptag_proxy_connection_str;
EXPORT tag_typedef_t httptag_proxy_connection_str_ref = 
  REFTAG_TYPEDEF(httptag_proxy_connection_str);
extern tag_typedef_t httptag_set_cookie;
EXPORT tag_typedef_t httptag_set_cookie_ref = 
  REFTAG_TYPEDEF(httptag_set_cookie);
extern tag_typedef_t httptag_set_cookie_str;
EXPORT tag_typedef_t httptag_set_cookie_str_ref = 
  REFTAG_TYPEDEF(httptag_set_cookie_str);
extern tag_typedef_t httptag_cookie;
EXPORT tag_typedef_t httptag_cookie_ref = 
  REFTAG_TYPEDEF(httptag_cookie);
extern tag_typedef_t httptag_cookie_str;
EXPORT tag_typedef_t httptag_cookie_str_ref = 
  REFTAG_TYPEDEF(httptag_cookie_str);
extern tag_typedef_t httptag_mime_version;
EXPORT tag_typedef_t httptag_mime_version_ref = 
  REFTAG_TYPEDEF(httptag_mime_version);
extern tag_typedef_t httptag_mime_version_str;
EXPORT tag_typedef_t httptag_mime_version_str_ref = 
  REFTAG_TYPEDEF(httptag_mime_version_str);
extern tag_typedef_t httptag_content_encoding;
EXPORT tag_typedef_t httptag_content_encoding_ref = 
  REFTAG_TYPEDEF(httptag_content_encoding);
extern tag_typedef_t httptag_content_encoding_str;
EXPORT tag_typedef_t httptag_content_encoding_str_ref = 
  REFTAG_TYPEDEF(httptag_content_encoding_str);
extern tag_typedef_t httptag_content_language;
EXPORT tag_typedef_t httptag_content_language_ref = 
  REFTAG_TYPEDEF(httptag_content_language);
extern tag_typedef_t httptag_content_language_str;
EXPORT tag_typedef_t httptag_content_language_str_ref = 
  REFTAG_TYPEDEF(httptag_content_language_str);
extern tag_typedef_t httptag_content_length;
EXPORT tag_typedef_t httptag_content_length_ref = 
  REFTAG_TYPEDEF(httptag_content_length);
extern tag_typedef_t httptag_content_length_str;
EXPORT tag_typedef_t httptag_content_length_str_ref = 
  REFTAG_TYPEDEF(httptag_content_length_str);
extern tag_typedef_t httptag_content_location;
EXPORT tag_typedef_t httptag_content_location_ref = 
  REFTAG_TYPEDEF(httptag_content_location);
extern tag_typedef_t httptag_content_location_str;
EXPORT tag_typedef_t httptag_content_location_str_ref = 
  REFTAG_TYPEDEF(httptag_content_location_str);
extern tag_typedef_t httptag_content_md5;
EXPORT tag_typedef_t httptag_content_md5_ref = 
  REFTAG_TYPEDEF(httptag_content_md5);
extern tag_typedef_t httptag_content_md5_str;
EXPORT tag_typedef_t httptag_content_md5_str_ref = 
  REFTAG_TYPEDEF(httptag_content_md5_str);
extern tag_typedef_t httptag_content_range;
EXPORT tag_typedef_t httptag_content_range_ref = 
  REFTAG_TYPEDEF(httptag_content_range);
extern tag_typedef_t httptag_content_range_str;
EXPORT tag_typedef_t httptag_content_range_str_ref = 
  REFTAG_TYPEDEF(httptag_content_range_str);
extern tag_typedef_t httptag_content_type;
EXPORT tag_typedef_t httptag_content_type_ref = 
  REFTAG_TYPEDEF(httptag_content_type);
extern tag_typedef_t httptag_content_type_str;
EXPORT tag_typedef_t httptag_content_type_str_ref = 
  REFTAG_TYPEDEF(httptag_content_type_str);
extern tag_typedef_t httptag_unknown;
EXPORT tag_typedef_t httptag_unknown_ref = 
  REFTAG_TYPEDEF(httptag_unknown);
extern tag_typedef_t httptag_unknown_str;
EXPORT tag_typedef_t httptag_unknown_str_ref = 
  REFTAG_TYPEDEF(httptag_unknown_str);
extern tag_typedef_t httptag_error;
EXPORT tag_typedef_t httptag_error_ref = 
  REFTAG_TYPEDEF(httptag_error);
extern tag_typedef_t httptag_error_str;
EXPORT tag_typedef_t httptag_error_str_ref = 
  REFTAG_TYPEDEF(httptag_error_str);
extern tag_typedef_t httptag_separator;
EXPORT tag_typedef_t httptag_separator_ref = 
  REFTAG_TYPEDEF(httptag_separator);
extern tag_typedef_t httptag_separator_str;
EXPORT tag_typedef_t httptag_separator_str_ref = 
  REFTAG_TYPEDEF(httptag_separator_str);
extern tag_typedef_t httptag_payload;
EXPORT tag_typedef_t httptag_payload_ref = 
  REFTAG_TYPEDEF(httptag_payload);
extern tag_typedef_t httptag_payload_str;
EXPORT tag_typedef_t httptag_payload_str_ref = 
  REFTAG_TYPEDEF(httptag_payload_str);
