/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum SipEventType {
  E_INVITE = tsip_event_invite,
  E_MESSAGE = tsip_event_message,
  E_OPTIONS = tsip_event_options,
  E_PUBLISH = tsip_event_publish,
  E_REGISTER = tsip_event_register,
  E_SUBSCRIBE = tsip_event_subscribe,
  E_DIALOG = tsip_event_dialog
}
