/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class SipSession : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SipSession(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SipSession obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SipSession() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        tinyWRAPPINVOKE.delete_SipSession(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public SipSession(SipStack Stack) : this(tinyWRAPPINVOKE.new_SipSession(SipStack.getCPtr(Stack)), true) {
  }

  public bool addHeader(string name, string value) {
    bool ret = tinyWRAPPINVOKE.SipSession_addHeader(swigCPtr, name, value);
    return ret;
  }

  public bool removeHeader(string name) {
    bool ret = tinyWRAPPINVOKE.SipSession_removeHeader(swigCPtr, name);
    return ret;
  }

  public bool addCaps(string name, string value) {
    bool ret = tinyWRAPPINVOKE.SipSession_addCaps__SWIG_0(swigCPtr, name, value);
    return ret;
  }

  public bool addCaps(string name) {
    bool ret = tinyWRAPPINVOKE.SipSession_addCaps__SWIG_1(swigCPtr, name);
    return ret;
  }

  public bool removeCaps(string name) {
    bool ret = tinyWRAPPINVOKE.SipSession_removeCaps(swigCPtr, name);
    return ret;
  }

  public bool setExpires(uint expires) {
    bool ret = tinyWRAPPINVOKE.SipSession_setExpires(swigCPtr, expires);
    return ret;
  }

  public bool setFromUri(string fromUri) {
    bool ret = tinyWRAPPINVOKE.SipSession_setFromUri(swigCPtr, fromUri);
    return ret;
  }

  public bool setToUri(string toUri) {
    bool ret = tinyWRAPPINVOKE.SipSession_setToUri(swigCPtr, toUri);
    return ret;
  }

  public bool setPayload(string str, uint len) {
    bool ret = tinyWRAPPINVOKE.SipSession_setPayload(swigCPtr, str, len);
    return ret;
  }

}
